### ISSUE TITLE
A problem when I run 'source project.tcl'

### ISSUE THREAD

**Issue by wenshh3** [skibo/RiscVAxi#1]
# set_property "xsim.array_display_limit" "64" $obj

ERROR: [Common 17-142] Invalid property name 'xsim.array_display_limit'.  Please use the 'list_property' command to find properties supported by the target 'project' object.

I never met such problem before, how can I do to address it? Thanks.

**Comment by skibo** [comment]
I just tried it on Vivado 2017.3 and it works.  But maybe you are using an older Vivado or a different simulator within Vivado?  Try commenting out or deleting the two lines in project.tcl that modify xsim properties (lines 120-121).  They are probably unnecessary.

**Comment by wenshh3** [comment]
Think you. I had commented those two lines and it worked.

**Comment by skibo** [comment]
I've committed the fix.
