### ISSUE TITLE
testfile compile problem

### ISSUE THREAD

**Issue by wenshh3** [skibo/RiscVAxi#2]
I have download the riscv toolchain in github, and I meet such problem:

![_20171122170622](https://user-images.githubusercontent.com/21306140/33118854-1b485716-cfa8-11e7-915c-22a21a1f6534.png)

**Comment by skibo** [comment]
You might have an older version of the toolchain.  If you look at the diffs for my last commit you can see the as options I previously used and what I changed.  But it's also possible you have a newer version of the toolchain and the assembler options have changed once again.

**Comment by skibo** [comment]
I just updated my toolchain (nov 7th 2017 release) and it broke.  Try replacing the "-m32" option with "-march=rv32g".  Also, my toolchain binaries now have the prefix "riscv64-unknown-elf-".  I'll see if I can fix up the Makefiles in the next several days.

**Comment by skibo** [comment]
I've committed some fixes to both RiscV_Arty and RiscVAxi.  One problem I also fixed is that I wasn't updating the submodule RiscVAxi within the RiscV_Arty project when I fixed things in the RiscVAxi repository.
